# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_APIKeySettings(object):
    def setupUi(self, APIKeySettings):
        APIKeySettings.setObjectName("APIKeySettings")
        APIKeySettings.resize(628, 429)
        self.verticalLayout = QtWidgets.QVBoxLayout(APIKeySettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(APIKeySettings)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 611, 58))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.binance_apikey = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.binance_apikey.setObjectName("binance_apikey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.binance_apikey)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.binance_secretkey = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.binance_secretkey.setObjectName("binance_secretkey")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.binance_secretkey)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 611, 58))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.hitbtc_apikey = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.hitbtc_apikey.setObjectName("hitbtc_apikey")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hitbtc_apikey)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hitbtc_secretkey = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.hitbtc_secretkey.setObjectName("hitbtc_secretkey")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hitbtc_secretkey)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 611, 58))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.kraken_apikey = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.kraken_apikey.setObjectName("kraken_apikey")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kraken_apikey)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.kraken_secretkey = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.kraken_secretkey.setObjectName("kraken_secretkey")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kraken_secretkey)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton = QtWidgets.QPushButton(APIKeySettings)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(APIKeySettings)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(APIKeySettings)

    def retranslateUi(self, APIKeySettings):
        _translate = QtCore.QCoreApplication.translate
        APIKeySettings.setWindowTitle(_translate("APIKeySettings", "Form"))
        self.label.setText(_translate("APIKeySettings", "API Key"))
        self.label_2.setText(_translate("APIKeySettings", "Sicret Key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("APIKeySettings", "Binance"))
        self.label_3.setText(_translate("APIKeySettings", "API Key"))
        self.label_4.setText(_translate("APIKeySettings", "Sicret Key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("APIKeySettings", "HitBtc"))
        self.label_5.setText(_translate("APIKeySettings", "API Key"))
        self.label_6.setText(_translate("APIKeySettings", "Sicret Key"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("APIKeySettings", "Kraaken"))
        self.pushButton.setText(_translate("APIKeySettings", "Ok"))

